networks:
  osm-net: 
    name: osm-net

volumes:
  osm-tmp:
  osm-storage:
  osm-db-data:
  certs:
  certbot_data:

services:
  proxy:
    image: "ghcr.io/hotosm/osm-sandbox/proxy:debug"
    profiles: [""]
    build:
      context: nginx
      target: debug
      args:
        NGINX_TAG: "${NGINX_TAG:-1.25.3}"
    depends_on:
      osm:
        condition: service_started
    ports:
      - ${OSM_DEV_PORT:-4433}:80
    networks:
      - osm-net
    restart: "unless-stopped"

  proxy-ssl:
    image: "ghcr.io/hotosm/osm-sandbox/proxy:latest"
    profiles: [public]
    build:
      context: nginx
      target: latest
      args:
        NGINX_TAG: "${NGINX_TAG:-1.25.3}"
    depends_on:
      osm:
        condition: service_started
      certbot:
        condition: service_completed_successfully
    volumes:
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - 80:80
      - 443:443
    networks:
      - osm-net
    restart: "unless-stopped"

  osm:
    image: ghcr.io/hotosm/osm-sandbox:2024.4.28
    build: .
    environment:
      PROTOCOL: http${DOMAIN:+s}
      DOMAIN: ${DOMAIN:-127.0.0.1:4433}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@hotosm.org}
      ADMIN_PASS: ${ADMIN_PASS:-Password1234}
      ID_EDITOR_REDIRECT_URI: http${DOMAIN:+s}://${DOMAIN:-127.0.0.1:4433}
    volumes:
      # Mount a tmp directory that will persist between runs
      - osm-tmp:/app/tmp
      # Mount a storage directory that will persist between runs
      - osm-storage:/app/storage
      # Mount local setting overrides
      # - ./settings.local.yml:/app/config/settings.local.yml:ro
    tmpfs:
      /tmp/pids/
    networks:
      - osm-net
    depends_on:
      osm-db:
        condition: service_healthy
    restart: unless-stopped

  osm-db:
    image: docker.io/postgres:14
    environment:
      POSTGRES_DB: openstreetmap
      POSTGRES_PASSWORD: openstreetmap
      POSTGRES_USER: openstreetmap
    volumes:
      - osm-db-data:/var/lib/postgresql/data
    networks:
      - osm-net
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U openstreetmap -d openstreetmap
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

  mail:
    image: "ixdotai/smtp:v0.5.2"
    volumes:
      - ./rsa.private:/etc/exim4/dkim.key.temp:ro
    environment:
      - MAILNAME=${DOMAIN:-hotosm.org}
      - DKIM_KEY_PATH=/etc/exim4/dkim.key.temp
    networks:
      - osm-net
    restart: unless-stopped

  certbot:
    image: "ghcr.io/hotosm/osm-sandbox/proxy:certs-init"
    profiles: [public]
    volumes:
      - certs:/etc/letsencrypt
      - certbot_data:/var/www/certbot
    environment:
      DOMAIN: ${DOMAIN}
      CERT_EMAIL: ${CERT_EMAIL}
    ports:
      - 80:80
      - 443:443
    networks:
      - osm-net
    restart: "on-failure:2"
